version: '1'

services:
  vision_pro:
    build:
      context: .
      dockerfile: /home/deepfine/data/docker/mob_gpt_visionOS_API/Dockerfile
    volumes:
      - shared-data:/home/deepfine/data/vision_pro
    ports:
      - "3535:3535"
    command:
      - node index.js
volumes:
  shared-data: