# 우분투 20.04 버전에서는 지원 안함
#version: '1'

services:
  vision_pro:
    build:
      context: /home/deepfine/data/docker/mob_gpt_visionOS_API
      dockerfile: /home/deepfine/data/docker/mob_gpt_visionOS_API/Dockerfile
    volumes:
      - shared-data:/home/deepfine/data/vision_pro
    ports:
      - "3535:3535"
volumes:
  shared-data: